import { writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { readManifestEntries } from "../lib/manifest.js";
import {
  ensureDirectory,
  ensureParentDirectory,
  pathExists,
  resolveProjectPath
} from "../lib/paths.js";

export const createGodotMonsterScenesInputSchema = {
  manifestPath: z.string().min(1),
  outputDir: z.string().min(1),
  sceneRootDir: z.string().min(1),
  baseScriptPath: z.string().min(1)
};

type CreateGodotMonsterScenesInput = z.infer<
  z.ZodObject<typeof createGodotMonsterScenesInputSchema>
>;

type MonsterManifestEntry = {
  id: string;
  name?: string;
  category?: string;
  family?: string;
  tier?: number;
  spritePath?: string;
  frameWidth?: number;
  frameHeight?: number;
  frameCount?: number;
  fps?: number;
  loop?: boolean;
  animation?: string;
};

function sanitizeFileName(input: string): string {
  return input.replace(/[^A-Za-z0-9_-]/g, "_");
}

function escapeGdString(input: string): string {
  return input.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildMonsterActorScript(): string {
  return `extends Node2D
class_name PixelForgeMonsterActor

@export var sprite_id: String = ""
@export var family: String = ""
@export var tier: int = 1


func get_summary() -> Dictionary:
\treturn {
\t\t"sprite_id": sprite_id,
\t\t"family": family,
\t\t"tier": tier
\t}
`;
}

function buildMonsterScenesReadme(sceneRootDir: string): string {
  return `# Godot Monster Scenes

This folder was generated by \`pixel-forge-mcp\`.

## What was generated

- One \`.tscn\` scene per monster manifest entry in the \`monsters\` category
- A shared \`MonsterActor.gd\` script under \`content/scripts/\`

## Scene structure

- The root node is a \`Node2D\` named after the monster id
- Static entries use \`Sprite2D\`
- Animation entries use \`AnimatedSprite2D\`
- Root metadata includes \`sprite_id\`, \`category\`, \`family\`, \`tier\`, and \`sprite_path\`

## Animation note

Animated scenes include an \`AnimatedSprite2D\` node and preserve animation metadata in scene metadata.

If a matching SpriteFrames resource exists at:

\`res://content/resources/spriteframes/<id>.tres\`

the generated scene will reference it automatically.

If no matching SpriteFrames resource exists yet, the scene is still generated and can be wired later.

## Suggested destination

Copy these scenes into:

\`res://${sceneRootDir.replace(/\\/g, "/")}\`
`;
}

function buildStaticScene(
  entry: MonsterManifestEntry,
  baseScriptPath: string
): string {
  const tier = Number.isFinite(entry.tier) ? Math.max(1, Number(entry.tier)) : 1;
  const family = escapeGdString(String(entry.family ?? ""));
  const spritePath = escapeGdString(String(entry.spritePath ?? ""));
  const category = escapeGdString(String(entry.category ?? ""));
  const id = escapeGdString(entry.id);

  return `[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="${baseScriptPath}" id="1"]
[ext_resource type="Texture2D" path="${spritePath}" id="2"]

[node name="${id}" type="Node2D"]
script = ExtResource("1")
metadata/sprite_id = "${id}"
metadata/category = "${category}"
metadata/family = "${family}"
metadata/tier = ${tier}
metadata/sprite_path = "${spritePath}"
sprite_id = "${id}"
family = "${family}"
tier = ${tier}

[node name="Sprite2D" type="Sprite2D" parent="."]
texture = ExtResource("2")
centered = true
`;
}

function buildAnimatedScene(
  entry: MonsterManifestEntry,
  baseScriptPath: string,
  spriteFramesPath: string | null
): string {
  const tier = Number.isFinite(entry.tier) ? Math.max(1, Number(entry.tier)) : 1;
  const family = escapeGdString(String(entry.family ?? ""));
  const spritePath = escapeGdString(String(entry.spritePath ?? ""));
  const category = escapeGdString(String(entry.category ?? ""));
  const id = escapeGdString(entry.id);
  const animation = escapeGdString(String(entry.animation ?? ""));
  const frameWidth = Number(entry.frameWidth ?? 0);
  const frameHeight = Number(entry.frameHeight ?? 0);
  const frameCount = Number(entry.frameCount ?? 0);
  const fps = Number(entry.fps ?? 0);
  const loop = Boolean(entry.loop ?? true);

  const header = spriteFramesPath
    ? `[gd_scene load_steps=3 format=3]

[ext_resource type="Script" path="${baseScriptPath}" id="1"]
[ext_resource type="SpriteFrames" path="${spriteFramesPath}" id="2"]`
    : `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="${baseScriptPath}" id="1"]`;

  const spriteFramesLine = spriteFramesPath ? `sprite_frames = ExtResource("2")\nautoplay = "${animation}"` : "";

  return `${header}

[node name="${id}" type="Node2D"]
script = ExtResource("1")
metadata/sprite_id = "${id}"
metadata/category = "${category}"
metadata/family = "${family}"
metadata/tier = ${tier}
metadata/sprite_path = "${spritePath}"
metadata/animation = "${animation}"
metadata/frame_width = ${frameWidth}
metadata/frame_height = ${frameHeight}
metadata/frame_count = ${frameCount}
metadata/fps = ${fps}
metadata/loop = ${String(loop).toLowerCase()}
sprite_id = "${id}"
family = "${family}"
tier = ${tier}

[node name="AnimatedSprite2D" type="AnimatedSprite2D" parent="."]
centered = true
${spriteFramesLine}
`;
}

export async function createGodotMonsterScenes(
  input: CreateGodotMonsterScenesInput
) {
  const { entries, manifestPath } =
    await readManifestEntries<MonsterManifestEntry>(input.manifestPath);
  const outputDir = resolveProjectPath(input.outputDir);
  const sceneRootDir = input.sceneRootDir.replace(/^\/+|\/+$/g, "");
  const scenesDir = path.join(outputDir, ...sceneRootDir.split("/"));
  const scriptsDir = path.join(outputDir, "content", "scripts");
  const actorScriptPath = path.join(scriptsDir, "MonsterActor.gd");
  const readmePath = path.join(scenesDir, "README_MONSTER_SCENES.md");

  await ensureDirectory(scenesDir);
  await ensureDirectory(scriptsDir);

  const generatedScenes: Array<{
    id: string;
    scenePath: string;
    nodeType: "Sprite2D" | "AnimatedSprite2D";
  }> = [];

  for (const entry of entries) {
    if (!entry.id) {
      throw new Error("Manifest entry is missing required field: id");
    }

    if (!entry.category) {
      throw new Error(`Manifest entry "${entry.id}" is missing required field: category`);
    }

    if (!entry.spritePath) {
      throw new Error(`Manifest entry "${entry.id}" is missing required field: spritePath`);
    }

    if (entry.category !== "monsters") {
      continue;
    }

    const safeFileName = sanitizeFileName(entry.id);
    if (!safeFileName) {
      throw new Error(`Manifest entry "${entry.id}" does not produce a safe scene filename`);
    }

    const scenePath = path.join(scenesDir, `${safeFileName}.tscn`);
    const isAnimated =
      typeof entry.frameCount === "number" &&
      entry.frameCount > 0 &&
      typeof entry.frameWidth === "number" &&
      entry.frameWidth > 0 &&
      typeof entry.frameHeight === "number" &&
      entry.frameHeight > 0;

    const spriteFramesRelativePath = `res://content/resources/spriteframes/${safeFileName}.tres`;
    const spriteFramesLocalPath = path.join(
      outputDir,
      "content",
      "resources",
      "spriteframes",
      `${safeFileName}.tres`
    );
    const spriteFramesPath =
      isAnimated && (await pathExists(spriteFramesLocalPath))
        ? spriteFramesRelativePath
        : null;

    const sceneText = isAnimated
      ? buildAnimatedScene(entry, input.baseScriptPath, spriteFramesPath)
      : buildStaticScene(entry, input.baseScriptPath);

    await ensureParentDirectory(scenePath);
    await writeFile(scenePath, sceneText, "utf8");

    generatedScenes.push({
      id: entry.id,
      scenePath,
      nodeType: isAnimated ? "AnimatedSprite2D" : "Sprite2D"
    });
  }

  await writeFile(actorScriptPath, buildMonsterActorScript(), "utf8");
  await writeFile(readmePath, buildMonsterScenesReadme(sceneRootDir), "utf8");

  return {
    manifestPath,
    outputDir,
    sceneRootDir,
    baseScriptPath: input.baseScriptPath,
    actorScriptPath,
    readmePath,
    sceneCount: generatedScenes.length,
    generatedScenes
  };
}
