import { writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { ensureDirectory, resolveProjectPath } from "../lib/paths.js";

export const createGodotLoaderStubInputSchema = {
  outputDir: z.string().min(1),
  className: z.string().regex(/^[A-Za-z_][A-Za-z0-9_]*$/)
};

type CreateGodotLoaderStubInput = z.infer<
  z.ZodObject<typeof createGodotLoaderStubInputSchema>
>;

function buildGdScript(className: string): string {
  return `extends Node
class_name ${className}

const MANIFEST_PATH := "res://content/sprite_manifest.json"

var _entries_by_id: Dictionary = {}
var _loaded: bool = false


func _ready() -> void:
\tload_manifest()


func load_manifest() -> bool:
\t_entries_by_id.clear()
\t_loaded = false

\tif not FileAccess.file_exists(MANIFEST_PATH):
\t\tpush_warning("Sprite manifest not found at %s" % MANIFEST_PATH)
\t\treturn false

\tvar file := FileAccess.open(MANIFEST_PATH, FileAccess.READ)
\tif file == null:
\t\tpush_warning("Unable to open sprite manifest at %s" % MANIFEST_PATH)
\t\treturn false

\tvar raw_text := file.get_as_text()
\tfile.close()

\tvar json := JSON.new()
\tvar parse_error := json.parse(raw_text)
\tif parse_error != OK:
\t\tpush_warning("Failed to parse sprite manifest JSON at %s" % MANIFEST_PATH)
\t\treturn false

\tvar data: Variant = json.data
\tif typeof(data) != TYPE_DICTIONARY:
\t\tpush_warning("Sprite manifest root must be a Dictionary.")
\t\treturn false

\tvar sprites: Variant = data.get("sprites", [])
\tif typeof(sprites) != TYPE_ARRAY:
\t\tpush_warning("Sprite manifest field 'sprites' must be an Array.")
\t\treturn false

\tfor sprite_variant in sprites:
\t\tif typeof(sprite_variant) != TYPE_DICTIONARY:
\t\t\tcontinue

\t\tvar sprite_entry: Dictionary = sprite_variant
\t\tvar sprite_id := String(sprite_entry.get("id", ""))
\t\tif sprite_id.is_empty():
\t\t\tcontinue

\t\t_entries_by_id[sprite_id] = sprite_entry.duplicate(true)

\t_loaded = true
\treturn true


func has_sprite(id: String) -> bool:
\treturn _entries_by_id.has(id)


func get_sprite(id: String) -> Dictionary:
\tif not _loaded and not load_manifest():
\t\treturn {}
\treturn _entries_by_id.get(id, {})


func get_sprite_path(id: String) -> String:
\tvar sprite := get_sprite(id)
\treturn String(sprite.get("spritePath", ""))


func get_animation(id: String) -> Dictionary:
\tvar sprite := get_sprite(id)
\tif sprite.is_empty():
\t\treturn {}

\tif not sprite.has("frameCount"):
\t\treturn {}

\treturn {
\t\t"id": String(sprite.get("id", "")),
\t\t"animation": String(sprite.get("animation", "")),
\t\t"spritePath": String(sprite.get("spritePath", "")),
\t\t"frameWidth": int(sprite.get("frameWidth", 0)),
\t\t"frameHeight": int(sprite.get("frameHeight", 0)),
\t\t"frameCount": int(sprite.get("frameCount", 0)),
\t\t"fps": float(sprite.get("fps", 0.0)),
\t\t"loop": bool(sprite.get("loop", true))
\t}


func list_by_category(category: String) -> Array[Dictionary]:
\tif not _loaded and not load_manifest():
\t\treturn []

\tvar matches: Array[Dictionary] = []
\tfor sprite_variant in _entries_by_id.values():
\t\tif typeof(sprite_variant) != TYPE_DICTIONARY:
\t\t\tcontinue

\t\tvar sprite_entry: Dictionary = sprite_variant
\t\tif String(sprite_entry.get("category", "")) == category:
\t\t\tmatches.append(sprite_entry.duplicate(true))

\treturn matches
`;
}

function buildLoaderReadme(className: string): string {
  return `# Godot Loader Stub

This folder was generated by \`pixel-forge-mcp\`.

## Where to copy the script

Copy \`godot/scripts/${className}.gd\` into your Godot 4 project, for example:

\`res://scripts/${className}.gd\`

## Autoload setup

1. Open **Project > Project Settings > Autoload**.
2. Add the copied script.
3. Use \`${className}\` as the autoload name if you want a matching singleton name.

The loader expects the manifest at:

\`res://content/sprite_manifest.json\`

## Example usage with Sprite2D

\`\`\`gdscript
var sprite_data := ${className}.get_sprite("slime_t1")
if not sprite_data.is_empty():
\t$Sprite2D.texture = load(${className}.get_sprite_path("slime_t1"))
\`\`\`

## Example usage with AnimatedSprite2D

\`\`\`gdscript
var animation_data := ${className}.get_animation("slime_t1_idle")
if not animation_data.is_empty():
\tprint(animation_data.frame_count)
\tprint(animation_data.fps)
\`\`\`

Animation metadata is preserved so you can map it into \`AnimatedSprite2D\` or \`SpriteFrames\` setup later.
`;
}

export async function createGodotLoaderStub(input: CreateGodotLoaderStubInput) {
  const outputDir = resolveProjectPath(input.outputDir);
  const scriptsDir = path.join(outputDir, "godot", "scripts");
  const scriptPath = path.join(scriptsDir, `${input.className}.gd`);
  const readmePath = path.join(scriptsDir, "README_GODOT_LOADER.md");

  await ensureDirectory(scriptsDir);
  await writeFile(scriptPath, buildGdScript(input.className), "utf8");
  await writeFile(readmePath, buildLoaderReadme(input.className), "utf8");

  return {
    outputDir,
    className: input.className,
    scriptPath,
    readmePath
  };
}
