import { writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { readManifestEntries } from "../lib/manifest.js";
import {
  ensureDirectory,
  ensureParentDirectory,
  pathExists,
  resolveProjectPath
} from "../lib/paths.js";

export const createGodotSpriteFramesInputSchema = {
  manifestPath: z.string().min(1),
  outputDir: z.string().min(1),
  spriteFramesDir: z.string().min(1)
};

type CreateGodotSpriteFramesInput = z.infer<
  z.ZodObject<typeof createGodotSpriteFramesInputSchema>
>;

type AnimationManifestEntry = {
  id: string;
  category?: string;
  spritePath?: string;
  frameWidth?: number;
  frameHeight?: number;
  frameCount?: number;
  fps?: number;
  loop?: boolean;
  animation?: string;
};

function sanitizeFileName(input: string): string {
  return input.replace(/[^A-Za-z0-9_-]/g, "_");
}

function buildSpriteFramesReadme(spriteFramesDir: string): string {
  return `# Godot SpriteFrames Resources

This folder was generated by \`pixel-forge-mcp\`.

## What was generated

- One \`.tres\` \`SpriteFrames\` resource for each manifest entry with animation metadata
- Each resource slices a sprite strip into per-frame \`AtlasTexture\` entries

## Current assumptions

- Animation strips are treated as horizontal strips
- The manifest must include \`frameWidth\`, \`frameHeight\`, \`frameCount\`, \`fps\`, \`loop\`, \`animation\`, and \`spritePath\`

## Current limitations

- Vertical strip metadata is not represented in the manifest yet, so vertical strip slicing is not generated automatically
- The generator assumes one strip image per animation entry
- The resulting resources are intended for \`AnimatedSprite2D\` scenes generated by Pixel Forge

## Suggested destination

Copy these resources into:

\`res://${spriteFramesDir.replace(/\\/g, "/")}\`
`;
}

function buildSpriteFramesResource(entry: Required<AnimationManifestEntry>): string {
  const subresources: string[] = [];
  const frameEntries: string[] = [];

  for (let index = 0; index < entry.frameCount; index += 1) {
    const subId = `AtlasTexture_${index + 1}`;
    const x = index * entry.frameWidth;

    subresources.push(`[sub_resource type="AtlasTexture" id="${subId}"]
atlas = ExtResource("1")
region = Rect2(${x}, 0, ${entry.frameWidth}, ${entry.frameHeight})`);

    frameEntries.push(`{
"duration": 1.0,
"texture": SubResource("${subId}")
}`);
  }

  return `[gd_resource type="SpriteFrames" load_steps=${entry.frameCount + 1} format=3]

[ext_resource type="Texture2D" path="${entry.spritePath}" id="1"]

${subresources.join("\n\n")}

[resource]
animations = [{
"frames": [${frameEntries.join(",\n")}],
"loop": ${String(entry.loop).toLowerCase()},
"name": &"${entry.animation}",
"speed": ${entry.fps}
}]
`;
}

export async function createGodotSpriteFrames(
  input: CreateGodotSpriteFramesInput
) {
  const { entries, manifestPath } =
    await readManifestEntries<AnimationManifestEntry>(input.manifestPath);
  const outputDir = resolveProjectPath(input.outputDir);
  const spriteFramesDir = input.spriteFramesDir.replace(/^\/+|\/+$/g, "");
  const resourcesDir = path.join(outputDir, ...spriteFramesDir.split("/"));
  const readmePath = path.join(resourcesDir, "README_SPRITEFRAMES.md");

  await ensureDirectory(resourcesDir);

  const generatedResources: Array<{
    id: string;
    resourcePath: string;
    animation: string;
  }> = [];

  for (const entry of entries) {
    const hasAnimationMetadata =
      typeof entry.frameWidth === "number" &&
      entry.frameWidth > 0 &&
      typeof entry.frameHeight === "number" &&
      entry.frameHeight > 0 &&
      typeof entry.frameCount === "number" &&
      entry.frameCount > 0 &&
      typeof entry.fps === "number" &&
      entry.fps > 0 &&
      typeof entry.animation === "string" &&
      entry.animation.length > 0 &&
      typeof entry.spritePath === "string" &&
      entry.spritePath.length > 0;

    if (!hasAnimationMetadata) {
      continue;
    }

    if (!entry.id) {
      throw new Error("Animation manifest entry is missing required field: id");
    }

    if (!entry.category) {
      throw new Error(`Animation manifest entry "${entry.id}" is missing required field: category`);
    }

    if (entry.category !== "monsters") {
      continue;
    }

    const safeFileName = sanitizeFileName(entry.id);
    if (!safeFileName) {
      throw new Error(`Animation manifest entry "${entry.id}" does not produce a safe filename`);
    }

    const resourcePath = path.join(resourcesDir, `${safeFileName}.tres`);
    const spritePath = String(entry.spritePath);
    const localSpritePath = spritePath.startsWith("res://")
      ? path.join(outputDir, spritePath.replace(/^res:\/\//, "").replace(/\//g, path.sep))
      : resolveProjectPath(spritePath);

    if (!(await pathExists(localSpritePath))) {
      throw new Error(
        `Animation sprite source not found for manifest entry "${entry.id}": ${spritePath}`
      );
    }

    const resourceText = buildSpriteFramesResource({
      id: entry.id,
      category: entry.category,
      spritePath,
      frameWidth: entry.frameWidth as number,
      frameHeight: entry.frameHeight as number,
      frameCount: entry.frameCount as number,
      fps: entry.fps as number,
      loop: Boolean(entry.loop ?? true),
      animation: entry.animation as string
    });

    await ensureParentDirectory(resourcePath);
    await writeFile(resourcePath, resourceText, "utf8");

    generatedResources.push({
      id: entry.id,
      resourcePath,
      animation: entry.animation as string
    });
  }

  await writeFile(readmePath, buildSpriteFramesReadme(spriteFramesDir), "utf8");

  return {
    manifestPath,
    outputDir,
    spriteFramesDir,
    readmePath,
    resourceCount: generatedResources.length,
    generatedResources
  };
}
